core/urls.py
import os

from django.urls import path, include, reverse_lazy
from django.conf.urls.static import static
from django.views.generic.base import TemplateView, RedirectView

from . import settings


urlpatterns = [
    path('robots.txt', TemplateView.as_view(template_name = 'core/robots.txt')),
    path('', include('flags.urls')),
    path('', RedirectView.as_view(  # Dummy view to provide site 'index' name
        url = reverse_lazy('flags:index'),
        permanent = True,
    ), name = 'index'),
]


if settings.DEBUG:
    urlpatterns += static(
        'favicon.ico',
        document_root = os.path.join(settings.BASE_DIR, 'core', 'static', 'favicon.ico'),
    )
    urlpatterns += static(
        'robots.txt',
        document_root = os.path.join(settings.BASE_DIR, 'core', 'static', 'robots.txt'),
    )

flags/urls.py
from django.urls import path

from . import views

app_name = 'flags'

urlpatterns = [
    path('flags/<slug:tag>/', views.FlagHistory.as_view(), name = 'flag_history'),
    path('advisories/<slug:tag>/', views.AdvisoryHistory.as_view(), name = 'advisory_history'),
    path('timelines/', views.Timelines.as_view(), name = 'timelines'),
    path('api/data-health/', views.data_health_api, name = 'data_health'),
    path('', views.Index.as_view(), name = 'index'),
]

flags/models.py
from datetime import timedelta

from django.db import models
from django.utils import timezone
from django.utils.functional import cached_property


class Reach(models.Model):
    """Describes a stretch of river."""
    
    class Common(models.TextChoices):
        ISIS = 'isis'
        GODS = 'godstow'
        RAD = 'radley'
        AB = 'abingdon'
        WALLI = 'wallingford'
        SAND = 'sandford'
    
    name = models.CharField(max_length = 12)
    tag = models.SlugField(max_length = 12, unique = True, choices = Common.choices)
    # ^ Implicit db index
    downstream_order = models.PositiveSmallIntegerField()
    has_ourcs_flag = models.BooleanField(default = False)
    
    class Meta:
        ordering = ['downstream_order']
    
    def __str__(self):
        return self.name
    
    
    @property
    def upstream_lock(self):
        return {
            self.Common.ISIS: 'Osney',
            self.Common.GODS: 'Godstow',
            self.Common.RAD: 'Sandford',
            self.Common.AB: 'Abingdon',
            self.Common.WALLI: 'Benson',
            self.Common.SAND: 'Iffley',
        }[self.tag]
    
    
    @property
    def downstream_lock(self):
        return {
            self.Common.ISIS: 'Iffley',
            self.Common.GODS: 'Osney',
            self.Common.RAD: 'Abingdon',
            self.Common.AB: 'Culham',
            self.Common.WALLI: 'Cleeve',
            self.Common.SAND: 'Sandford',
        }[self.tag]
    
    
    @cached_property
    def current_flag_status(self):
        """The most recently shown OURCs flag for the reach."""
        return self.statuses.all().first()
    
    
    @cached_property
    def current_advisory(self):
        """The most recently shown EA stream advisory for the reach.
        
        N.B. Filtering by current time leads to issue #1.
        """
        return self.advisories.all().first()
    
    
    def update_flag_status(self, new_flag, set_at, set_by = ''):
        """Updates the OURCs flag status to reflect the latest observation."""
        
        # Update existing matching flag
        if self.current_flag_status and self.current_flag_status.flag == new_flag:
            
            if not self.current_flag_status.set_by:
                self.current_flag_status.set_by = set_by
            
            self.current_flag_status.last_seen = timezone.now()
            self.current_flag_status.save()
        
        # Create new status if mismatched or missing
        else:
            self.statuses.create(
                flag = new_flag,
                set_at = set_at,
                set_by = set_by,
            )
        
        # Reset current flag cache
        del self.current_flag_status
    
    
    def update_advisory(self, new_board, board_shown = timezone.now()):
        """Updates EA advisory records to reflect `new_board` being displayed at `board_shown`."""
        
        # Short outages are ignored at first
        if (
            new_board == Advisory.Boards.OUT
            and not self.current_advisory.board == Advisory.Boards.OUT
            and self.current_advisory.last_seen >= timezone.now() - timedelta(hours = 24)
        ):
            return
        
        # Update existing matching advisory if no significant gap
        if (
            self.current_advisory and self.current_advisory.board == new_board
            and self.current_advisory.last_seen >= timezone.now() - timedelta(hours = 24)
        ):
            self.current_advisory.last_updated = board_shown
            self.current_advisory.last_seen = timezone.now()
            self.current_advisory.save()
        
        # Mismatched or missing advisory
        else:
        
            # Create additional outage report if significant time gap
            if (
                self.current_advisory and new_board != Advisory.Boards.OUT
                and self.current_advisory.last_seen <= timezone.now() - timedelta(hours = 4)
            ):
                self.advisories.create(
                    board = Advisory.Boards.OUT,
                    first_seen = self.current_advisory.last_seen + timedelta(hours = 1),
                    first_updated = self.current_advisory.last_updated + timedelta(hours = 1),
                    last_seen = timezone.now() - timedelta(hours = 1),
                    last_updated = board_shown - timedelta(hours = 1),
                )
            
            # Create new advisory
            self.advisories.create(
                board = new_board,
                first_updated = board_shown,
                last_updated = board_shown,
            )
        
        # Reset current advisory cache
        del self.current_advisory


class Status(models.Model):
    """Describes the raising of an OURCs flag."""
    
    class Flags(models.TextChoices):
        GREY = ('X', 'Grey')
        GREEN = ('G', 'Green')
        LIGHT = ('L', 'Light Blue')
        BLUE = ('B', 'Blue')
        AMBER = ('A', 'Amber')
        RED = ('R', 'Red')
        BLACK = ('D', 'Black')
        OUTAGE = ('O', 'Outage')
    
    reach = models.ForeignKey(Reach, models.CASCADE, related_name = 'statuses')
    flag = models.CharField(max_length = 1, choices = Flags.choices)
    set_at = models.DateTimeField()
    set_by = models.CharField(max_length = 50, blank = True)
    
    first_seen = models.DateTimeField(default = timezone.now)
    last_seen = models.DateTimeField(default = timezone.now)
    
    class Meta:
        ordering = ['reach', '-set_at']
    
    def __str__(self):
        return self.get_flag_display()
    
    @property
    def out_of_date(self):
        return (timezone.now() - self.last_seen) > timedelta(hours = 2)
    
    def styling(self):
        return {
            self.Flags.GREY: 'bg-secondary',
            self.Flags.GREEN: 'bg-success',
            self.Flags.LIGHT: 'bg-lightblue',
            self.Flags.BLUE: 'bg-primary',
            self.Flags.AMBER: 'bg-warning',
            self.Flags.RED: 'bg-danger text-light',
            self.Flags.BLACK: 'bg-dark text-light',
            self.Flags.OUTAGE: 'bg-secondary',
        }.get(self.flag)


class Advisory(models.Model):
    """A private model describing EA stream advisories for use through the Reach model.
    
    first_seen - When board first seen (by our retrievals)
    first_updated - When board first displayed (according to EA)
    last_seen - When board last seen (by our retrievals)
    last_updated - When board last affirmed (according to EA)
    """
    
    class Boards(models.TextChoices):
        NONE = ('NONE', 'No advisory')
        INC = ('INC', 'Caution (Increasing)')
        DEC = ('DEC', 'Caution (Decreasing)')
        RED = ('RED', 'Danger')
        OUT = ('OUT', 'Outage')
    
    reach = models.ForeignKey(Reach, models.CASCADE, related_name = 'advisories')
    board = models.CharField(max_length = 4, choices = Boards.choices)
    
    first_seen = models.DateTimeField(default=timezone.now)
    first_updated = models.DateTimeField(default=timezone.now)
    last_seen = models.DateTimeField(default=timezone.now)
    last_updated = models.DateTimeField(default=timezone.now)
    
    class Meta:
        ordering = ['reach', '-first_updated']
    
    def __str__(self):
        return self.get_board_display()
    
    @property
    def out_of_date(self):
        return (timezone.now() - self.last_seen) > timedelta(hours = 2)
    
    def styling(self):
        return {
            self.Boards.NONE: 'bg-none',
            self.Boards.INC: 'bg-warning',
            self.Boards.DEC: 'bg-warning',
            self.Boards.RED: 'bg-danger',
            self.Boards.OUT: 'bg-secondary text-white',
        }[self.board]

flags/views.py
from datetime import timedelta

from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from django.http import JsonResponse
from django.utils import timezone

from . import models, transits, analysis


class FlagNavMixin:
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'all_reaches': models.Reach.objects.all(),
            'flag_reaches': models.Reach.objects.filter(has_ourcs_flag = True).order_by('pk'),
        })
        return context


class Index(FlagNavMixin, TemplateView):
    
    template_name = 'flags/index.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        context['all_reaches'] = context['all_reaches'].prefetch_related('advisories')
        context['flag_reaches'] = context['flag_reaches'].prefetch_related('statuses')
        
        context['transits'] = transits.generate_transit_information(
            context['flag_reaches'],
            context['all_reaches'],
        )
        
        return context


class FlagHistory(FlagNavMixin, DetailView):
    
    model = models.Reach
    queryset = models.Reach.objects.filter(has_ourcs_flag = True).prefetch_related('statuses')
    slug_field = 'tag'
    slug_url_kwarg = 'tag'
    template_name = 'flags/flag_history.html'


class AdvisoryHistory(FlagNavMixin, DetailView):
    
    model = models.Reach
    queryset = models.Reach.objects.prefetch_related('advisories')
    slug_field = 'tag'
    slug_url_kwarg = 'tag'
    template_name = 'flags/advisory_history.html'


class Timelines(FlagNavMixin, TemplateView):
    
    template_name = 'flags/timelines.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        today = timezone.now().date()
        context['timeline_data'] = analysis.get_statuses_and_advisories_by_date(today)
        return context


def data_health_api(request):
    """Reports on the oldest flag status and advisory, and whether any outages are recorded."""
    
    def flag_health_ordering(flag_status):
        """Ordered by last seen, with future scope for outages."""
        return (True, flag_status.last_seen)
    
    def advisory_health_ordering(advisory):
        """Ordered by last seen, with trump for outages."""
        return (advisory.board != models.Advisory.Boards.OUT, advisory.last_seen)
    
    reaches = list(models.Reach.objects.all())
    
    current_flags = [reach.current_flag_status for reach in reaches if reach.has_ourcs_flag]
    current_flags.sort(key = flag_health_ordering)
    least_healthy_flag = current_flags[0]
    
    current_advisories = [reach.current_advisory for reach in reaches]
    current_advisories.sort(key = advisory_health_ordering)
    least_healthy_advisory = current_advisories[0]
    
    data_healthy = (
        current_flags[0].last_seen >= timezone.now() - timedelta(hours = 4)
        and least_healthy_advisory.board != models.Advisory.Boards.OUT
        and least_healthy_advisory.last_seen >= timezone.now() - timedelta(hours = 4)
    )
    
    return JsonResponse({
        'health': 'HEALTHY' if data_healthy else 'DATED',
        'oldestCurrentFlag': {
            'reach': least_healthy_flag.reach.tag,
            'status': least_healthy_flag.flag,
            'lastSeen': least_healthy_flag.last_seen,
        },
        'oldestCurrentAdvisory': {
            'reach': least_healthy_advisory.reach.tag,
            'advisory': least_healthy_advisory.board,
            'lastSeen': least_healthy_advisory.last_seen,
        },
    })

flags/templates/flags/advisory_history.html
{% extends 'flags/base.html' %}

{% block title %}Oxford Rivers - {{ reach }}{% endblock %}

{% block page_body %}
    
    <!-- Out-of-date notice -->
    {% if reach.current_advisory.out_of_date %}<div class="row"><div class="col"><div class="alert alert-danger" role="alert">
      We have not been able to check the boards for this reach in over two hours.
      For up-to-date information you can <a href="http://riverconditions.environment-agency.gov.uk" class="alert-link" target="_blank">check the EA website directly</a>.
    </div></div></div>{% endif %}
    <!-- Out-of-date notice -->
    
    <!-- Overview -->
    <div class="row">
      <div class="col-md-7">
        <h1 class="mb-0">{{ reach }}</h1>
        <div>{{ reach.upstream_lock }} Lock to {{ reach.downstream_lock }} Lock</div>
      </div>
      
      <div class="col-md-5">
        <div class="card card-standalone {{ reach.current_advisory.styling }}">
          <div class="card-body">
            <h4 class="card-title text-center"><strong>{{ reach.current_advisory }}</strong></h4>
            <table class="table table-sm table-borderless {{ reach.current_advisory.styling }}">
              <tr>
                <td class="text-left p-0">Last updated:</td>
                <td class="text-right p-0">{{ reach.current_advisory.last_updated|date:"d/m/Y H:i" }}</td>
              </tr>
              <tr>
                <td class="text-left p-0">Last seen:</td>
                <td class="text-right p-0">{{ reach.current_advisory.last_seen|date:"d/m/Y H:i" }}</td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
    <!-- Overview -->
    
    <!-- Interpretation guide -->
    <div class="row"><div class="col">
      <div class="card card-dropdown">
        <div
            id="interpretationHeader"
            class="card-header d-flex justify-content-between"
            type="button"
            data-toggle="collapse"
            data-target="#interpretationBody"
            style="border-bottom: 0px"
        >
          <span>How to interpret this information</span>
          <span class="oi oi-chevron-bottom" id="interpretationArrow"></span>
        </div>
        <div class="collapse" id="interpretationBody"><div class="card-body">
          <p>
            The EA issues stream advisories for stretches of the Thames between two locks which are displayed to river traffic as physical boards on the lock at each end of the stretch<sup>*</sup>.
            These are also made available online on their <a href="http://riverconditions.environment-agency.gov.uk/" target="_blank">river conditions website</a> and we collect the information about the boards shown from this website.
            However, the website does not update automatically, instead providing a "Page Last Updated" indicator so there may be a delay between physical boards changing on the lock and the boards changing on their website<sup>**</sup>.
          </p>
          <p>
            We poll the river conditions website on a slightly randomised five-minute interval and note both the time the website was last changed (the <em>updated</em> time) and the actual time of the collection run (the <em>seen</em> time)<sup>***</sup>.
            For each advisory observed, we record the updated and seen times for both the first and last observations of that advisory.
          </p>
          <p>
            Between the first and last updated times for an advisory, it will have been displayed to traffic transiting onto that stretch, but between the last updated time of one advisory and the first updated time of the next advisory, the boards will have changed on the lock and it is not possible to say precisely when this would have happened.
            Similarly, between the first and last seen times for an advisory, it will have been shown on the website for that stretch.
            The website will have changed between the last seen time of one advisory and the first seen time of the next advisory, but since collection is performed roughly every five minutes, the scope for variation here is much lower<sup>****</sup>.
          </p>
          <p>
            Monitoring outages can occur for a variety of reasons.
            An outage is recorded for posterity when monitoring has been down for over four hours and observes a different advisory when it resumes.
            If the same advisory as before the outage is observed when monitoring resumes, then it is only recorded for posterity if it lasted longer than 24 hours.
            This is because the EA indicate that they only update the boards once per day, so a change to a different status and back to the original within those 24 hours is unlikely.
          </p>
          <p>
            <sup>*</sup> A lock may display different boards to upstream and downstream traffic, since they apply to the next stretch of river, rather than the lock itself.
            <br/>
            <sup>**</sup> As far as we are aware, the information shown at the update time will always match what is shown at the lock at that moment.
            <br/>
            <sup>***</sup> Both are recorded to to help identify discrepancies between when the EA report the page was updated and when we observed the change, whether caused by technical issues or other systemic delays.
            <br/>
            <sup>****</sup> It is possible that a data collection outage might entirely miss a change and change-back of an advisory, but this is unlikely since the boards typically change on a scale of days, and the website only appears to update a couple of times a day.
          </p>
        </div></div>
      </div>
    </div></div>
    <!-- Interpretation guide -->
    
    <!-- Past advisories table -->
    <div class="row"><div class="col">
      <table class="table table-sm table-borderless table-responsive-md text-center">
        <thead class="thead-light"><tr>
          <th class="align-middle">Board</th>
          <th class="align-middle">First Updated</th>
          <th class="align-middle">First Seen</th>
          <th class="align-middle">Last Updated</th>
          <th class="align-middle">Last Seen</th>
        </tr></thead>
        {% for advisory in reach.advisories.all %}<tr class="{{ advisory.styling }}">
          <th class="align-middle">{{ advisory.get_board_display }}</th>
          <td class="align-middle">{{ advisory.first_updated|date:"d/m/Y H:i" }}</td>
          <td class="align-middle">{{ advisory.first_seen|date:"d/m/Y H:i" }}</td>
          <td class="align-middle">{{ advisory.last_updated|date:"d/m/Y H:i" }}</td>
          <td class="align-middle">{{ advisory.last_seen|date:"d/m/Y H:i" }}</td>
        </tr>{% endfor %}
      </table>
    </div></div>
    <!-- Past advisories table -->
    
    <script type="text/javascript">
      $('#interpretationBody').on('show.bs.collapse', function () {
        $('#interpretationArrow').removeClass('oi-chevron-bottom').addClass('oi-chevron-top');
        $('#interpretationHeader').css('border-bottom', '');
      });
      $('#interpretationBody').on('hidden.bs.collapse', function () {
        $('#interpretationArrow').removeClass('oi-chevron-top').addClass('oi-chevron-bottom');
        $('#interpretationHeader').css('border-bottom', '0px');
      })
    </script>
{% endblock %}

flags/templates/flags/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <title>{% block title %}Oxford Rivers{% endblock %}</title>
  
  <!-- Bootstrap resources -->  
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css" integrity="sha256-BJ/G+e+y7bQdrYkS2RBTyNfBHpA9IuGaPmf9htub5MQ=" crossorigin="anonymous" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Bootstrap resources -->
  
  <!-- Site resources -->
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}" >
  <link rel="stylesheet" type="text/css" href="{% static 'flags/main.css' %}">{% block page_head %}
  {% endblock %}<!-- Site resources -->
</head>
<body>
{% include 'flags/nav.html' %}
  <div class="container">
    <div class="row"><div class="col"><!-- Page-top spacing --></div></div>
    
    <!-- Main page body -->
    {% block page_body %}
    {% endblock %}
    <!-- Main page body -->
    
  </div>
</body>
</html>

flags/templates/flags/index.html
{% extends 'flags/base.html' %}
{% load flag_tags %}

{% block page_body %}
    <!-- OURCs Flags -->
    <div class="row">
      <div class="col">
        <h2>OURCs Flags</h2>
        <p>
          Restriction levels for college crews that are set by OURCs and made available <a href="https://ourcs.co.uk/information/flags/" target="_blank">on their website</a>.
          They are primarily based on stream levels, but can also be set for other reasons in exceptional circumstances.
        </p>
      </div>
    </div>
    <div class="row">
      {% for reach in flag_reaches %}<div class="col">
        <div class="card">
          <div class="card-header">
            {{ reach }}
          </div>
          <div class="card-body {% if reach.current_flag_status.out_of_date %}text-light bg-secondary{% else %}{{ reach.current_flag_status.styling }}{% endif %}">
            <span class="card-title"><strong>{{ reach.current_flag_status }}{% if reach.current_flag_status.out_of_date %} (Out of date){% endif %}</strong></span>
            <br/>
            <span>{{ reach.current_flag_status.set_at|date:"d/m/Y" }} {{ reach.current_flag_status.set_at|date:"H:i" }}</span>
          </div>
          <a href="{% url 'flags:flag_history' reach.tag %}" class="card-footer text-dark d-flex justify-content-between">
            <div>View History</div>
            <div><span class="oi oi-chevron-right"></span></div>
          </a>
        </div>
      </div>{% endfor %}
    </div>
    <!-- OURCs Flags -->
    
    <!-- Transits --->
    <div class="row">
      <div class="col">
        <h2>Transits</h2>
        <p>
          As of December 2020, rowing boats are only allowed to transit a lock if there are no stream advisories on either side of that lock, and all relevant OURCs flags are green (or equivalent grey).
          Launches may transit locks on yellow boards (a "Caution" advisory) if a risk assessment has been approved by the RowSab, and are not restricted by the Isis (or Godstow) flag.
        </p>
      </div>
    </div>
    <div class="row">
      {% for transit in transits %}<div class="col-md-4">
        <div class="card">
          <div class="card-header">
            {{ transit.destination|capfirst }} Transit
          </div>
          <div class="card-body p-0">
            <table class="table table-sm text-center">
              {% transit_allowed_row 'Boats' transit.rowing True %}{% transit_allowed_row 'Launches' transit.launches %}
            </table>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <!-- Transits --->

    <!-- EA Advisories -->
    <div class="row">
      <div class="col">
        <h2>EA Advisories</h2>
        <p>
          These are the latest advisories we have seen on the EA's <a href="http://riverconditions.environment-agency.gov.uk/" target="_blank">river conditions webpage</a>.
          They are checked roughly every five minutes.
        </p>
      </div>
    </div>
    <div class="row">
      {% for reach in all_reaches %}
      <div class="col-lg-2">
        <div class="card">
          <div class="card-header">
            {{ reach }}
          </div>
          <div class="card-body {% if reach.current_advisory.out_of_date %}text-light bg-secondary{% else %}{{ reach.current_advisory.styling }}{% endif %}">
            <span class="card-title"><strong>{{ reach.current_advisory }}{% if reach.current_advisory.out_of_date %} (Out of date){% endif %}</strong></span>
            <br/>
            <span>{{ reach.current_advisory.first_updated|date:"d/m/Y" }}</span>
            <span>{{ reach.current_advisory.first_updated|date:"H:i" }}</span>
          </div>
          <a href="{% url 'flags:advisory_history' reach.tag %}" class="card-footer text-dark d-flex justify-content-between">
            <div>View History</div>
            <div><span class="oi oi-chevron-right"></span></div>
          </a>
        </div>
      </div>
      {% endfor %}
    </div>
    <!-- EA Advisories -->
{% endblock %}

flags/templates/flags/nav.html
  <!-- Navbar -->
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'index' %}">Oxford Rivers</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar_content">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbar_content">
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="" role="button" data-toggle="dropdown">
            OURCs Flags
          </a>
          <div class="dropdown-menu">{% for nav_reach in flag_reaches %}
            <a class="dropdown-item" href="{% url 'flags:flag_history' nav_reach.tag %}">{{ nav_reach }}</a>{% endfor %}
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="" role="button" data-toggle="dropdown">
            EA Advisories
          </a>
          <div class="dropdown-menu">{% for nav_reach in all_reaches %}
            <a class="dropdown-item" href="{% url 'flags:advisory_history' nav_reach.tag %}">{{ nav_reach }}</a>{% endfor %}
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'flags:timelines' %}">Timelines</a>
        </li>
      </ul>
    </div>
  </nav>
  <!-- Navbar -->